### ISSUE TITLE
Add server metrics/logging

### ISSUE THREAD

**Issue by jaredkerim** [mozilla-services/location-leaderboard#180]
Add health monitoring and server metrics to the backend, probably through DataDog.  Work with ops @ckolos to integrate with their monitoring infrastructure.

**Comment by jaredkerim** [comment]
@ckolos What should we use for this?  Is ops using DataDog now?

**Comment by ckolos** [comment]
yup. You should be able to send any stats that you wish to aggregate to localhost:8125 via udp. From there it will be sent along to datadog.

**Comment by jaredkerim** [comment]
We need to pick this up and log

1) calls to fxa for frequency and duration
2) aggregation computation frequency and duration
3) i'd like to know api endpoint call frequency/duration

These should all be logged to statsd and picked up by datadog
