### ISSUE TITLE
Support __heartbeat__ route on web server

### ISSUE THREAD

**Issue by ckolos** [mozilla-services/location-leaderboard#184]
Should return a 200 if "all is well".

**Comment by jaredkerim** [comment]
@ckolos what do you think I should check with this?  Database connectivity?  I think that the only two services to check the health of are 1) the web nodes 2) the database.  The only other thing would be the aggregation worker process, maybe I should keep a log of when that process runs and just make sure that it has run within some specified timeout.

**Comment by ckolos** [comment]
I believe that other apps use this route as a) a DB check and b) a semi-simulated transaction check. I'm cool with that approach; i.e. Can I lookup "foo", yup. Okay, return 200.

**Comment by hannosch** [comment]
`__heartbeat__` is also typically used in the ELB to check if a web node is up and it should send traffic to it. Therefor I wouldn't check the aggregation worker status, or the worker not being run would result in the ELB to remove all web nodes and thus the website being unreachable.

**Comment by ckolos** [comment]
Agreed. For __heartbeat__ we would only want to check the bits that the public sees.
