### ISSUE TITLE
Add an FXA refresh token endpoint 

### ISSUE THREAD

**Issue by jaredkerim** [mozilla-services/location-leaderboard#215]
Add an endpoint which will receive a refresh_token from a client, and exchange it for a new access_token and return it to the client.

See here:

https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1token

**Comment by crankycoder** [comment]
Sample working refresh token endpoint is here:

https://github.com/crankycoder/fxa-android/blob/features/refresh_tokens/sample_endpoint/example_server.py 

I'll be merging that branch of the fxa-android code into the primary dev branch today, and upgrading the stumbler as well.
