### ISSUE TITLE
Profile page doesn't seem to be loading correctly

### ISSUE THREAD

**Issue by crankycoder** [mozilla-services/location-leaderboard#216]
I'm using my FxA UID to try loading a profile page, but I'm not getting any data. 

http://leaderboard-dev.jaredkerim.com/?profile=86638715e74d47279251adca928a5f74

**Comment by jaredkerim** [comment]
You can't use the FXA UID, you have to use the Leaderboard UID.  The point of creating a leaderboard UID which is separate from the FXA UID is that we shouldn't leak the FXA UID to other users.  All calls to leaderboard which expect a UID should expect the Leaderboard UID.

**Comment by crankycoder** [comment]
Hrm. I'm trying to use '87c7fcaee20f43e1975cd9cb99465345' and I'm still getting nothing.


http://leaderboard-dev.jaredkerim.com/?profile=87c7fcaee20f43e1975cd9cb99465345

**Comment by crankycoder** [comment]
The response blob I'm getting is: 

```json
{"access_token":"3fde9ce78bf691785b2881ea1906e1a0690b4b6e74e1b3bbe5ee57a3d025c070","uid":"87c7fcaee20f43e1975cd9cb99465345"}
```

**Comment by jaredkerim** [comment]
Yeah this is related to #195 #196 #214 which is to pass back the FXA data as well as the Leaderboard UID (which used to be the same but are now separate uids) so several things need to change in the backend before this all fits together properly.
