### ISSUE TITLE
Do not sent POST body to Sentry

### ISSUE THREAD

**Issue by jaredkerim** [mozilla-services/location-leaderboard#261]
We presently use Sentry to log exceptions, however this will send the POST body in its entirety to our ops controlled sentry instance which will contain unobfuscated URLs which come from users histories.  We should be omitting or obfuscating this in some way to prevent leaking users histories.

**Comment by jaredkerim** [comment]
@relud @jvehent @mostlygeek Feedback?

**Comment by relud** [comment]
I definitely think it should be omitted

**Comment by mostlygeek** [comment]
I favor omission too. Are there circumstances where having the URLs would help with debugging? If not, then they definitely should be omitted.

**Comment by jvehent** [comment]
Aye, let's omit and reduce the number of places where we store user sensitive stuff.

**Comment by jaredkerim** [comment]
Okay I was not paying attention.  This is the wrong repo.
