### ISSUE TITLE
Are old leaderboard-ranks lost? 

### ISSUE THREAD

**Issue by sesom** [mozilla-services/location-leaderboard#284]
Till now I used MozStumbler without a Firefox-account and MozStumbler v1.8.4 tells me I uploaded 141191 reports so far. Today I registered a Firefox-account and the [new leaderboard](https://location-leaderboard.services.mozilla.com/?iso2=DE&offset=10) shows just 4 reports for me.

Well I know, it's about collecting data and not about statistics, but  loosing 140000+ reports hurts a little bit. Is there a way to get them back? My username is "Dizzy".

**Comment by jaredkerim** [comment]
@sesom Unfortunately, the old leaderboard did not actually track accounts or identity in any way, so there is no way to correlate those entries to the new leaderboard, so everybody has to start over from 0 on the new system.  We're sorry there wasn't a better way to save your points from the old leaderboard, but the good news is that the work and data collected was definitely not lost, all of your data contributions are intact and helping the Mozilla Geolocation Service!
