### ISSUE TITLE
Missing Content Security Policy Header

### ISSUE THREAD

**Issue by g-k** [mozilla-services/location-leaderboard#302]
Adding a CSP header would provide a backstop to mitigate XSS.

https://developer.mozilla.org/en-US/docs/Web/Security/CSP
https://wiki.mozilla.org/Security/CSP

https://observatory.mozilla.org/analyze.html?host=location-leaderboard.services.mozilla.com

**Comment by g-k** [comment]
I can pick this up if no one is working on it.

**Comment by jaredkerim** [comment]
Fixed by #303
